### ISSUE TITLE
Add pane labels to reference and production pane

### ISSUE THREAD

**Issue by emersonk** [kseaman/Capstone3DModelling#57]
The two top panes need to have labels on them so that the user knows which is the reference pane and which is the production pane

**Comment by zifangah** [comment]
is this associated to vtk renders labels? for now I have issue with bad access exception from vtk since vtk is not linked yet to Qt  (same as Dana), so i have trouble doing work with vtk with that exception;
i was able to before the merge of unified alignment happened because it was taking local argument, but now its taking arguments from Qt, which is not passed;
thoughts?
so far i'll look into how to build something that does the same thing as the .exe file Emerson and Karn has

**Comment by zifangah** [comment]
Changes made on Pane-label branch
